[package]
name = "icu4x-key-extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icu_datagen = { path = "../../../icu4x/provider/datagen" }
